### ISSUE TITLE
It needs a requirements.txt file

### ISSUE THREAD

**Issue by king-dahmanus** [mush42/tashkeel#2]
Hey again! So upon attempting to make a liiiiittle program to use the library, I encountered a module import error that said I didn't have a module named onnxruntime. So, can you add a requirements.txt file to use, so all the needed packages can be easily installed?

**Comment by mush42** [comment]
Hi @king-dahmanus  
This project uses [Poetry](https://python-poetry.org/) for managing dependencies.
Please take a look at it's docs to know how to install the dependencies.
